name: 'Preternatural Build Action'
description: 'Run Preternatural build command on repositories with a specified Xcode version'
inputs:
  derived_data_path:
    description: 'The path to the derived data folder'
    required: false
  platforms:
    description: 'Target platforms (array of: iOS, macOS, tvOS, watchOS, visionOS, all)'
    required: false
    default: '["macOS"]'
  xcode-version:
    description: 'Xcode version to use'
    required: true
  configurations:
    description: 'Build configurations (array of: debug, release)'
    required: false
    default: '["debug", "release"]'
runs:
  using: 'composite'
  steps:
    - name: Install Preternatural
      if: ${{ !env.ACT }} # Skipping when run locally.
      shell: bash
      run: |
        brew tap PreternaturalAI/preternatural
        brew install preternatural
    - name: Cache derived data
      uses: actions/cache@v3
      if: ${{ !env.ACT }} # Skipping when run locally.
      with:
        path: ${{ inputs.derived_data_path || '~/Library/Developer/Xcode/DerivedData' }}
        key: ${{ runner.os }}-derived-data-xcode-${{ inputs.xcode-version }}
        restore-keys: |
          ${{ runner.os }}-derived-data-xcode-${{ inputs.xcode-version }}
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}
      
    - name: Execute Preternatural build command
      id: build
      shell: bash
      run: |
        defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
        COMMAND="preternatural build"
        if [ -n "${{ inputs.derived_data_path }}" ]; then
          COMMAND="$COMMAND --derived-data-path '${{ inputs.derived_data_path }}'"
        fi

        # Handle platforms array
        PLATFORMS="${{ join(fromJSON(inputs.platforms), ',') }}"
        if [ -n "$PLATFORMS" ]; then
          COMMAND="$COMMAND --platforms '$PLATFORMS'"
        fi
        
        # Handle configurations array
        CONFIGS="${{ join(fromJSON(inputs.configurations), ',') }}"
        if [ -n "$CONFIGS" ]; then
          COMMAND="$COMMAND --configurations '$CONFIGS'"
        fi

        echo "Executing command: $COMMAND"
        eval $COMMAND
        
    - name: Find and copy all xcactivity logs
      if: failure()
      shell: bash
      run: |
        if [ -n "${{ inputs.derived_data_path }}" ]; then
          DERIVED_DATA_PATH="${{ inputs.derived_data_path }}"
        else
          DERIVED_DATA_PATH="$HOME/Library/Developer/Xcode/DerivedData"
        fi
        echo "Searching for logs in: $DERIVED_DATA_PATH"
        
        mkdir -p ./artifacts
        
        # Find all xcactivitylog files and copy them to the artifacts directory
        find "$DERIVED_DATA_PATH" -name "*.xcactivitylog" -type f -print0 | while IFS= read -r -d '' log; do
          cp "$log" "./artifacts/$(basename "$log")"
          echo "Copied $log to ./artifacts/"
        done
        
        # Debug information
        echo "List of copied log files:"
        ls -l ./artifacts/*.xcactivitylog
        echo "Total size of copied logs:"
        du -sh ./artifacts
        
        # Check if any logs were found and copied
        if [ -z "$(ls -A ./artifacts)" ]; then
          echo "No xcactivitylog files found in $DERIVED_DATA_PATH"
          exit 1
        fi

    - name: Install xclogparser
      if: failure()
      shell: bash
      run: |
        brew install xclogparser

    - name: Convert logs to JSON and print
      if: failure()
      shell: bash
      run: |
        mkdir -p ./json_logs
        for log in ./artifacts/*.xcactivitylog; do
          json_file="./json_logs/$(basename "$log" .xcactivitylog).json"
          xclogparser parse --file "$log" --output "$json_file"
          echo "Contents of $json_file:"
          cat "$json_file"
          echo "--------------------------------"
        done

    - name: Upload xcactivity logs (JSON)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: xcactivity-logs-json
        path: ./json_logs/*.json
        if-no-files-found: error

    - name: Upload xcactivity logs (Raw)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: xcactivity-logs-raw
        path: ./artifacts/*.xcactivitylog
        if-no-files-found: error
