name: 'Preternatural Build Action'
description: 'Run Preternatural build command on repositories with a specified Xcode version'
inputs:
  derived_data_path:
    description: 'The path to the derived data folder'
    required: false
  build_all_platforms:
    description: 'Builds for all supported platforms'
    required: false
    default: 'false'
  xcode-version:
    description: 'Xcode version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Preternatural
      shell: bash
      run: |
        brew tap PreternaturalAI/preternatural
        brew install preternatural

    - name: Cache derived data
      uses: actions/cache@v3
      with:
        path: ${{ inputs.derived_data_path || '~/Library/Developer/Xcode/DerivedData' }}
        key: ${{ runner.os }}-derived-data-xcode-${{ inputs.xcode-version }}
        restore-keys: |
          ${{ runner.os }}-derived-data-xcode-${{ inputs.xcode-version }}

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}
      
    - name: Execute Preternatural build command
      shell: bash
      run: |
        COMMAND="preternatural build"
        if [ -n "${{ inputs.derived_data_path }}" ]; then
          COMMAND="$COMMAND --derived-data-path '${{ inputs.derived_data_path }}'"
        fi
        if [ "${{ inputs.build_all_platforms }}" == "true" ]; then
          COMMAND="$COMMAND --build-all-platforms"
        fi
        echo "Executing command: $COMMAND"
        eval $COMMAND